// <auto-generated />
using System;
using ASP.NETCore_STYLiSH_Back_End.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETCore_STYLiSH_Back_End.Migrations
{
    [DbContext(typeof(StylishContext))]
    partial class StylishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Campaign", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("Picture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("picture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Story")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("story")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ProductId")
                        .HasName("PK_campaign_product_id");

                    b.ToTable("campaign", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Hot", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Products")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("products")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Title")
                        .HasName("PK_hots_title");

                    b.ToTable("hots", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("LastFour")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("last_four")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("OrderProducts")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("order_products")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("Pay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("pay")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("PayOrders")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pay_orders")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Payment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Shipping")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shipping")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Time")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("time")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("User")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("UserOrders")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_orders")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("OrderId")
                        .HasName("PK_orders_order_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Otherimage", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ImagesUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("images_url")
                        .HasDefaultValueSql("(NULL)");

                    b.HasIndex("Id");

                    b.ToTable("otherimages", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("MainImage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("main_image")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Place")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("place")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Story")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("story")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Texture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("texture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Wash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("wash")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK_product_id");

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Password")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Picture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("picture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK_user_id");

                    b.HasIndex(new[] { "Email" }, "user$email_UNIQUE")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Variant", b =>
                {
                    b.Property<string>("ColorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("color_code")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ColorName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("color_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Size")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("size")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock")
                        .HasDefaultValueSql("(NULL)");

                    b.ToTable("variant", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Otherimage", b =>
                {
                    b.HasOne("ASP.NETCore_STYLiSH_Back_End.Models.Product", "IdNavigation")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("otherimages$otherimages_ibfk_1");

                    b.Navigation("IdNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
