// <auto-generated />
using ASP.NETCore_STYLiSH_Back_End.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NETCore_STYLiSH_Back_End.Migrations
{
    [DbContext(typeof(StylishContext))]
    partial class StylishContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Campaign", b =>
                {
                    b.Property<long>("ProductId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_id");

                    b.Property<string>("Picture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("picture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Story")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("story")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("ProductId")
                        .HasName("PK_campaign_product_id");

                    b.ToTable("campaign", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 201807242228L,
                            Picture = "http://localhost:5130/images/201807242228.jpg",
                            Story = "於是\n我也想要給你\n一個那麼美好的自己。\n不朽《與自己和好如初》"
                        },
                        new
                        {
                            ProductId = 201807202140L,
                            Picture = "http://localhost:5130/images/201807202140.jpg",
                            Story = "瞬間\n在城市的角落\n找到失落多時的記憶。\n印象《都會故事集》"
                        },
                        new
                        {
                            ProductId = 201807242222L,
                            Picture = "http://localhost:5130/images/201807242222.jpg",
                            Story = "永遠\n展現自信與專業\n無法抵擋的男人魅力。\n復古《再一次經典》"
                        });
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Hot", b =>
                {
                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Products")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("products")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Title")
                        .HasName("PK_hots_title");

                    b.ToTable("hots", (string)null);

                    b.HasData(
                        new
                        {
                            Title = "熱門商品",
                            Products = "201807201824,201807202140,201807242222"
                        });
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("order_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("LastFour")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("last_four")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("OrderProducts")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("order_products")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<short?>("Pay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("pay")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("PayOrders")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pay_orders")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Payment")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("payment")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Shipping")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("shipping")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Time")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("time")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Total")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("total")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("User")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("UserOrders")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_orders")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("OrderId")
                        .HasName("PK_orders_order_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Otherimage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ImagesUrl")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("images_url")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK_otherimage");

                    b.ToTable("otherimages", (string)null);
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("category")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Description")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("description")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("MainImage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("main_image")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Note")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("note")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Place")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("place")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Price")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("price")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Story")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("story")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Texture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("texture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Wash")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("wash")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK_product_id");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 201807201824L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807201824.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 799,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "前開衩扭結洋裝",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807202140L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807202140.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 599,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "透肌澎澎防曬襯衫",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807202150L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807202150.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 599,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "小扇紋細織上衣",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807202157L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807202157.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 1299,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "活力花紋長筒牛仔褲",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242211L,
                            Category = "men",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242211.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 799,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "純色輕薄百搭襯衫",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242216L,
                            Category = "men",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242216.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 2399,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "時尚輕鬆休閒西裝",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242222L,
                            Category = "men",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242222.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 3999,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "經典商務西裝",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242228L,
                            Category = "accessories",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242228.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 1499,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "夏日海灘戶外遮陽帽",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242230L,
                            Category = "accessories",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242230.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 799,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "經典牛仔帽",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242232L,
                            Category = "accessories",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242232.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 1299,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "卡哇伊多功能隨身包",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201807242234L,
                            Category = "accessories",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201807242234.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 1799,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "柔軟氣質羊毛圍巾",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201902191210L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201902191210.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 999,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "精緻扭結洋裝",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201902191242L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201902191242.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 999,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "透肌澎澎薄紗襯衫",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201902191245L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201902191245.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 999,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "小扇紋質感上衣",
                            Wash = "手洗，溫水"
                        },
                        new
                        {
                            Id = 201902191247L,
                            Category = "women",
                            Description = "厚薄：薄\r\n彈性：無",
                            MainImage = "http://localhost:5130/images/products/201902191247.jpg",
                            Note = "實品顏色依單品照為主",
                            Place = "中國",
                            Price = 1999,
                            Story = "O.N.S is all about options, which is why we took our staple polo shirt and upgraded it with slubby linen jersey, making it even lighter for those who prefer their summer style extra-breezy.",
                            Texture = "棉 100%",
                            Title = "經典修身長筒牛仔褲",
                            Wash = "手洗，溫水"
                        });
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Password")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Picture")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("picture")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("provider")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id")
                        .HasName("PK_user_id");

                    b.HasIndex(new[] { "Email" }, "user$email_UNIQUE")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("user", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 38,
                            Email = "test@gmail.com",
                            Name = "test",
                            Password = "90e2cd6afaf9cdef6eb243188c6d09247658dfc06feb2ca784c67a4220bbd4e4",
                            Picture = "http",
                            Provider = "facebook"
                        },
                        new
                        {
                            Id = 39,
                            Email = "test2@gmail.com",
                            Name = "test",
                            Password = "90e2cd6afaf9cdef6eb243188c6d09247658dfc06feb2ca784c67a4220bbd4e4",
                            Picture = "http",
                            Provider = "native"
                        });
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Variant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ColorCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("color_code")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("Size")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("size")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<string>("ColorName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("color_name")
                        .HasDefaultValueSql("(NULL)");

                    b.Property<int?>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stock")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("Id", "ColorCode", "Size")
                        .HasName("PK_variant");

                    b.ToTable("variant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 201807201824L,
                            ColorCode = "FFFFFF",
                            Size = "S",
                            ColorName = "白色",
                            Stock = 2
                        },
                        new
                        {
                            Id = 201807201824L,
                            ColorCode = "FFFFFF",
                            Size = "M",
                            ColorName = "白色",
                            Stock = 2
                        },
                        new
                        {
                            Id = 201807201824L,
                            ColorCode = "FFFFFF",
                            Size = "L",
                            ColorName = "白色",
                            Stock = 2
                        },
                        new
                        {
                            Id = 201807202140L,
                            ColorCode = "DDFFBB",
                            Size = "S",
                            ColorName = "亮綠",
                            Stock = 12
                        },
                        new
                        {
                            Id = 201807202140L,
                            ColorCode = "DDFFBB",
                            Size = "M",
                            ColorName = "亮綠",
                            Stock = 10
                        },
                        new
                        {
                            Id = 201807202140L,
                            ColorCode = "DDFFBB",
                            Size = "L",
                            ColorName = "亮綠",
                            Stock = 10
                        });
                });

            modelBuilder.Entity("ASP.NETCore_STYLiSH_Back_End.Models.Otherimage", b =>
                {
                    b.HasOne("ASP.NETCore_STYLiSH_Back_End.Models.Product", "IdNavigation")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("otherimages$otherimages_ibfk_1");

                    b.Navigation("IdNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
